version: '3.1'

services:

  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: social_network
  app:
    image: rsavin/social-network
    restart: always
    ports:
      - 8080:8080